[build-system]
requires = ["setuptools>=56", "setuptools_scm[toml]>=3.4.1"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | \.venv
    | __pycache__
    | .+\.egg-info
    | build
    | dist
  )
)
'''

[tool.setuptools_scm]

[tool.pytest-enabler.black]
addopts = "--black"

[tool.pytest-enabler.mypy]
addopts = "--mypy"

[tool.pytest-enabler.cov]
addopts = "--cov"

[tool.pytest-enabler.ruff]
addopts = "--ruff"
