name: Pre-merge and post-merge tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml
    # https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
    if: >
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      matrix:
        python:
        - "3.8"
        - "3.11"
        - "3.12"
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        include:
        - python: "3.9"
          platform: ubuntu-latest
        - python: "3.10"
          platform: ubuntu-latest
        - python: pypy3.9
          platform: ubuntu-latest
    with:
      python-version: ${{ matrix.python }}
      platform: ${{ matrix.platform }}

  docs:
    name: Build documentation
    uses: ./.github/workflows/docs.yml
    # https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
    if: >
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

  check:  # This job does nothing and is only used for the branch protection
    # https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
    if: >
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    needs:
    - test
    - docs

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
